module.exports = {
  apps: [
    {
      name: 'ai-canvaspro',
      script: 'server.py',
      interpreter: 'python',
      interpreter_args: '-u',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '512M',
      autorestart: true,
      watch: false,
      ignore_watch: [
        'node_modules',
        '.git',
        '*.log',
        'user-data',
        'cam-output',
        '__pycache__',
        '*.pyc',
      ],
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        AICANVAS_PORT: 8777,
        AIC_BIND_HOST: '127.0.0.1',
        DESIGN_TEAM_DB_HOST: '127.0.0.1',
        DESIGN_TEAM_DB_PORT: '3306',
        DESIGN_TEAM_DB_USER: 'root',
        DESIGN_TEAM_DB_PASSWORD: 'zw246888',
        DESIGN_TEAM_DB_NAME: 'design_team_db',
        AIC_AUTH_TOKEN_SECRET: 'aicanvaspro-default-secret-change-in-production',
        AIC_JWT_SECRET: 'design-team-jwt-secret-change-in-production',
        PYTHONUNBUFFERED: '1',
      },
      error_file: './logs/err.log',
      out_file: './logs/out.log',
      log_file: './logs/combined.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      time: true,
      kill_timeout: 5000,
      wait_ready: false,
      listen_timeout: 10000,
    },
  ],
};